### ISSUE TITLE
Some channels are not working

### ISSUE THREAD

**Issue by dagwieers** [add-ons/plugin.video.tvvlaanderen#13]
I found that the following channels are not working in the TV Vlaanderen add-on:
- Baby TV (only distorted audio, no video)
- ATV (Antwerpen)
- TVL (Limburg)
- TVO (Oost-Vlaanderen)
- (18+) Hustler TV

The Baby TV stream is not working in the TV Vlaanderen Android app or website either.
The ATV, TVL and  TVO streams are not working as well in the TV Vlaanderen Android app or website.
And Hustler TV is not even listed in the Android app, but requires an "ouderlijk toezichtscode", and since I do not know what it is, I also cannot change it in my profile settings.

Everything else is working as expected.

I also noticed that TV App Light abo offers 35 channels, but we get 38 channels on the website and in Kodi, and 37 channels in the android app (because Hustler TV is missing).

**Comment by michaelarnauts** [comment]
ATV, TVL and TVO are currently out of service. I've contacted support for this. They are aware of the issue.

I haven't checked into Hustler, but it might require some additional code for the PIN validation. On the website, there is a setting to define the minimum age level that requires a PIN, I assume the same setting exists in Android.

**Comment by michaelarnauts** [comment]
> I also noticed that TV App Light abo offers 35 channels, but we get 38 channels on the website and in Kodi, and 37 channels in the android app (because Hustler TV is missing).

Huh, it currently even indicates 34 channels on the homepage. Probably due to the broken channels. It was 38 when I took the subscription.

**Comment by michaelarnauts** [comment]
ATV, TVL and TVO have been removed from their offering. The other channels are working now.
