### ISSUE TITLE
Cannot view Streams on Raspberry Pi 3 wih LibreElec

### ISSUE THREAD

**Issue by Vankerkom** [add-ons/plugin.video.tvvlaanderen#19]
Hello, the current release version does not allow me to play any streams on the Raspberry PI 3 With LibreElec 9.2.6. (Kodi 18.9)

**Stacktrace:**

> 
> 2020-11-11 16:39:26.362 T:1475335040   DEBUG: AddOnLog: InputStream Adaptive: Searching for decrypters in: /usr/lib/kodi/addons/inputstream.adaptive/
> 2020-11-11 16:39:26.362 T:1475335040   ERROR: GetDirectory - Error getting /usr/lib/kodi/addons/inputstream.adaptive/
> 2020-11-11 16:39:26.362 T:1475335040   DEBUG: AddOnLog: InputStream Adaptive: Searching for decrypters in: /storage/.kodi/addons/inputstream.adaptive
> 2020-11-11 16:39:26.365 T:1937536048   DEBUG: CPlayerGUIInfo::InitCurrentItem(pvr://channels/tv/All channels/pvr.iptvsimple_1582414803.pvr)
> 2020-11-11 16:39:26.378 T:1937536048   DEBUG: CVideoGUIInfo::InitCurrentItem(pvr://channels/tv/All channels/pvr.iptvsimple_1582414803.pvr)
> 2020-11-11 16:39:26.378 T:1937536048   DEBUG: CPlayerGUIInfo::InitCurrentItem(pvr://channels/tv/All channels/pvr.iptvsimple_1582414803.pvr)
> 2020-11-11 16:39:26.404 T:1475335040   DEBUG: AddOnLog: InputStream Adaptive: Found decrypter: /storage/.kodi/addons/inputstream.adaptive/libssd_wv.so
> 2020-11-11 16:39:26.404 T:1475335040   DEBUG: AddOnLog: InputStream Adaptive: Supported URN: urn:uuid:[OMITTED]
> 2020-11-11 16:39:26.405 T:1475335040   DEBUG: CurlFile::Open(0x5e981c88) https://tvvvideolive.solocoo.tv/dashtvv/smil:l1.ism/manifest.mpd
> 2020-11-11 16:39:26.412 T:1807721344   DEBUG: CWebServer[8080]: request received for /jsonrpc
> 2020-11-11 16:39:26.520 T:1475335040   DEBUG: AddOnLog: InputStream Adaptive: Effective URL https://tvvvideolive.solocoo.tv/dashtvv/smil:l1.ism/manifest.mpd
> 2020-11-11 16:39:26.521 T:1475335040   DEBUG: AddOnLog: InputStream Adaptive: Download https://tvvvideolive.solocoo.tv/dashtvv/smil:l1.ism/manifest.mpd finished
> 2020-11-11 16:39:26.522 T:1475335040    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Periods: 1, #Streams in first period: 2, Type: live, Download speed: 0.0000 Bytes/s
> 2020-11-11 16:39:26.523 T:1475335040   DEBUG: CAddonSettings[inputstream.adaptive]: loading setting definitions
> 2020-11-11 16:39:26.527 T:1475335040   DEBUG: Previous line repeats 1 times.
> 2020-11-11 16:39:26.527 T:1475335040   DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
> 2020-11-11 16:39:26.528 T:1475335040   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)
> 2020-11-11 16:39:26.528 T:1475335040   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
> 2020-11-11 16:39:26.528 T:1475335040   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()
> 2020-11-11 16:39:26.529 T:1475335040   ERROR: CVideoPlayer::OpenInputStream - error opening [pvr://channels/tv/All channels/pvr.iptvsimple_1582414803.pvr]
> 2020-11-11 16:39:26.530 T:1475335040  NOTICE: CVideoPlayer::OnExit()

**Suggestion:**

I've been searching online and found a script that gave me the the following output log:

> The widevine library should now be installed (and updated) by
> script.module.inpustreamhelper.
> 
> script.module.inputstreamhelper will be installed automatically as a dependency
> when installing video addons (Netflix etc.) from a suitable repository.
> 
> Contact the video add-on author if the video add-on does not support
> script.module.inputstreamhelper.

**Comment by mediaminister** [comment]
For the TV Vlaanderen add-on you need to manually install InputStream Helper add-on. Just search in "Search add-ons" for "inputstream helper". Or manually install the zip release from: https://github.com/emilsvennesson/script.module.inputstreamhelper/releases

**Comment by michaelarnauts** [comment]
De addon depend al op inputstream.helper vreemd dat je geen meldingen kreeg.

Het lijkt erop dat je geen Widevine library hebt geïnstalleerd. Wat gebeurd er als je live wil kijken via de TV Vlaanderen addon zelf? Misschien dat je de eerste keer moet afspelen vanaf de Addon zelf?

Na een update van Widevine kan het ook helpen om Kodi eens te herstarten.

**Comment by mediaminister** [comment]
No, there is no inputstreamhelper implemented yet.

**Comment by michaelarnauts** [comment]
> No, there is no inputstreamhelper implemented yet.

Oow, that would explain this 👍
