### ISSUE TITLE
Er start niets op

### ISSUE THREAD

**Issue by chris20800** [add-ons/plugin.video.tvvlaanderen#21]

**Comment by chris20800** [comment]
Versie 18.9
Kanalen en epg laden in.
Noch live kijken of replay werken

**Comment by chris20800** [comment]
Opgelost

**Comment by michaelarnauts** [comment]
Probeer in het vervolg meer info te geven, alsook wat de oplossing was. Dat kan later iemand verder helpen met hetzelfde probleem.
