### ISSUE TITLE
Channel EEN stopped working

### ISSUE THREAD

**Issue by beligum** [add-ons/plugin.video.tvvlaanderen#33]
Hi there, 

I'm not entirely sure I didn't do something wrong myself, but channel één stopped working here. AFAIK all other channels stream perfectly.
Do any others experience issues with Één? 

B.

**Comment by mediaminister** [comment]
Eén livestream works. Please provide a log, if you need help to solve your problem: https://kodi.wiki/view/Log_file/Easy

**Comment by beligum** [comment]
Ah, that's good news. The bad news is it doesn't work in my case :-(
Canvas works though, so I wonder what the issue with één seems to be.

I'm attaching the log of a fresh kodi session (redacted a bit to wipe the
credentials) where I enable debug log first, then try to switch to the één
channel.
It seems to start throwing errors around line 730. Don't really know what
errors are critical and which ones are acceptable.
Would you mind taking a look?

best,

b.

**Comment by beligum** [comment]
No idea why @mediaminister his comment and my attached log seems to have vanished, but here's my log file again: [kodi.log](https://github.com/add-ons/plugin.video.tvvlaanderen/files/6714551/kodi.log)

**Comment by mediaminister** [comment]
I was wrong. There is indeed a problem with Eén. I'll take a look at it.

**Comment by mediaminister** [comment]
The http request of the MPEG-DASH manifest fails.
```
2021-06-25 11:37:44.802 T:26329   ERROR <general>: CCurlFile::FillBuffer - Failed: Stream error in the HTTP/2 framing layer(92)
2021-06-25 11:37:44.802 T:26329   ERROR <general>: CCurlFile::Open failed with code 0 for https://tvvvideolive3.solocoo.tv/blueskytvvlive7dash/blueeen/manifest.mpd:
```
Then I tried the request using the Linux command line and this works. 
```
curl 'https://tvvvideolive3.solocoo.tv/blueskytvvlive7dash/blueeen/Manifest.mpd'
```
Not sure why curl is failing in Kodi.

**Comment by beligum** [comment]
Just a hunch, but could it be http2 isn't supported (yet) in the kodi version of curl?
I'm running kodi on a nvidia shield, so it's kind of hard to ssh into it and test it manually here.
Is there anything I can do to help?

**Comment by mediaminister** [comment]
I have a TV Vlaanderen account myself, so I can test everything. I disabled http2 in advancedsettings.xml, I got a different error, but it still fails.
```
2021-06-25 11:56:51.410 T:28235   ERROR <general>: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
```
```
<advancedsettings>
  <loglevel>1</loglevel>
  <network>
    <disablehttp2>true</disablehttp2> 
  </network>
</advancedsettings>
```
I can do some more tests, but I currently have no clue why it fails.

>  Is there anything I can do to help?

You can look online for a solution or clue regarding these curl errors in Kodi.

**Comment by beligum** [comment]
How about forcing it to http2? Maybe the tvvlaanderen server is switching/switched to http2 recently?

**Comment by michaelarnauts** [comment]
It's due to the User-Agent. When it contains Kodi, they reject to give a Manifest. Currently, it seems that this is only happening on één.

**Comment by beligum** [comment]
whow, they must not like us then ;-)

**Comment by michaelarnauts** [comment]
Can you try with this ZIP?

[plugin.video.tvvlaanderen-1.0.4-dev+matrix.1-user-agent-6a0caa9.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/6715798/plugin.video.tvvlaanderen-1.0.4-dev%2Bmatrix.1-user-agent-6a0caa9.zip) (matrix)
[plugin.video.tvvlaanderen-1.0.4-dev-user-agent-6a0caa9.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/6715799/plugin.video.tvvlaanderen-1.0.4-dev-user-agent-6a0caa9.zip) (leia)

**Comment by beligum** [comment]
Allright, will try this weekend

**Comment by beligum** [comment]
Works like a charm!

**Comment by michaelarnauts** [comment]
Thanks for verifying, I'll make a new release.
