### ISSUE TITLE
Channel Één not working on raspberry 3 and 4

### ISSUE THREAD

**Issue by countrytaste** [add-ons/plugin.video.tvvlaanderen#36]
I made on a new memory card a total new setup.
With the app of TV Vlaanderen Chanel één does not works.
Canvas , vtm, the duch channels works perfect

thank you

**Comment by michaelarnauts** [comment]
I have tried this on my system (ubuntu on a pc), and it seems to work fine with the latest version.

Can you provide more details about your system and upload a log of the failed playback?

See https://kodi.wiki/view/Log_file/Easy

**Comment by countrytaste** [comment]
Dag Michael,

Dank voor je antwoord.
Ik kijk dus via raspberry, raspberry 3 en raspberry 4.
Ik installeerde kodi 18.9 via Librelec 9.2.6
Daarna installeerde ik de add-on van TV. Vlaanderen 1.0.4
Kies ik hiermee kanalen, en dan één dan gebeurt er niets, ik krijg geen foutmelding.
Dus ik vermoed dat de log file niks zal aantonen.
Kies ik canvas dan werkt alles perfect net zoals alle andere zenders.
Ik heb voor TVV twee accounts, en bij beide is dezelfde fout.
Nog even vermelden, VRT.nu , VTMgo, goPlay kanalenlijst Hans werken perfect.

Dank bij voorbaat

Bernard

**Comment by michaelarnauts** [comment]
Zonder log kan ik niets zien, en ga ik je niet kunnen helpen.

**Comment by countrytaste** [comment]
Toch bedankt, Michael, eigenaardig maar vandaag werkt het weer perfect.
Misschien komt het probleem wel van de vrt zelf……

Groeten

**Comment by michaelarnauts** [comment]
@countrytaste ik neem aan dat het ondertussen correct werkt? Zeker dat je de laatste versie had?

Net nog geprobeerd op Linux, en daar werkt één HD prima. Het kan natuurlijk zijn er een probleem is op ARM, en het dus niet werkt op een Raspberry Pi, dat hebben we bij andere streams ook al gezien (rzie https://github.com/add-ons/plugin.video.viervijfzes/issues/69)
