### ISSUE TITLE
TV Vlaanderen: Terugkijk TV niet te vinden

### ISSUE THREAD

**Issue by doglover3920** [add-ons/plugin.video.tvvlaanderen#37]
**Describe the bug**
Replay TV, bekijk een programma tot 7 dagen terug (niet voor alle zenders)
Kan dit niet vinden.  Geeft allen de Channels weer. Niets te vinden van terugkijk TV

**System**
 - Addon version: v1.0.4.
 - Kodi version: 18.9 leia
 - Inputstream adaptive version:
 - Operating System (Windows / Mac OS / Android / LibreElec / OSMC / ...): Enigma2
 - Special Hardware (RPI / Vero4K+ / ...): HiSil

**Comment by michaelarnauts** [comment]
Open eens een channel in de Add-on. :)

**Comment by doglover3920** [comment]
Sorry....
