### ISSUE TITLE
Focussat Romania

### ISSUE THREAD

**Issue by derzis** [add-ons/plugin.video.tvvlaanderen#41]
Hi. Can you add Focussat Romania?  The correct domain is domain='livetv.focussat.ro' and env seems to be env='m7cz2iphone'.
Thank you

**Comment by michaelarnauts** [comment]
I've build an ZIP here: https://github.com/add-ons/plugin.video.tvvlaanderen/pull/42#issuecomment-1014648483

I can't test if this works, so please let me know if it does :)

**Comment by derzis** [comment]
If you need i can send you the Kodi logs and credentials for Focussat
Romania.
Cheers

În lun., 17 ian. 2022 la 16:13, Michaël Arnauts ***@***.***>
a scris:

**Comment by michaelarnauts** [comment]
You can send me an email at michael.arnauts@gmail.com.

**Comment by michaelarnauts** [comment]
If you want, you can always help out to add a translation in Romanian :)

**Comment by derzis** [comment]
Hi. Here is romanian translation. Thank you again.

În mar., 18 ian. 2022 la 10:16, Michaël Arnauts ***@***.***>
a scris:

**Comment by michaelarnauts** [comment]
I see no attachment, but can you create a pull request? If not, please upload it at this ticket on github itself.

**Comment by derzis** [comment]
Here is romanian translation
[strings.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/7891833/strings.zip)

**Comment by michaelarnauts** [comment]
Thanks @derzis for your help! I've submitted the branded Add-on to the Kodi repository. It's still unsure if it will end up in the Leia repository, since they don't accept new Add-ons there, but it will be in Matrix for sure!
