### ISSUE TITLE
Tv-vlaanderen 'retro view' doesn't work anymore

### ISSUE THREAD

**Issue by steenkapper** [add-ons/plugin.video.tvvlaanderen#59]
Hello who can help me with this?
TV Flanders with Kodi, retrospective TV no longer works !

VB: TV guide for (ex) VTM
Today (enter)
response: tv flanders error
check the log for more information

thanks in advance

**Comment by steenkapper** [comment]
Hallo wie kan mij hiermede helpen ?
Tv-vlaanderen met kodi, terugkijk-tv werkt niet meer !

VB: TV guide voor (ex)VTM
Today (enter)
reactie: tv vlaanderen error
check the log for more information

**Comment by michaelarnauts** [comment]
Duplicate of #60
