### ISSUE TITLE
Retro-view on tv vlaanderen

### ISSUE THREAD

**Issue by steenkapper** [add-ons/plugin.video.tvvlaanderen#60]
Kodi 20.2
Smart tv
Add-on:  tv-vlaanderen

rertro/view does not work any more

![image](https://github.com/add-ons/plugin.video.tvvlaanderen/assets/81979729/a3701f61-81e1-425d-a4ac-fb40a4da3c35)

**Comment by michaelarnauts** [comment]
I don't have a TV Vlaanderen subscription anymore unfortunately, so I can't check myself.

I would need to have access to your logs to see what's going on.

Make sure to check in your browser on your profile page that you have not used all your device registrations. If it is, just remove an old one.

**Comment by mediaminister** [comment]
Please test:
Kodi 18: [plugin.video.tvvlaanderen-1.0.6.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/12167938/plugin.video.tvvlaanderen-1.0.6.zip)
Kodi 19/20/21: [plugin.video.tvvlaanderen-1.0.6+matrix.1.zip](https://github.com/add-ons/plugin.video.tvvlaanderen/files/12167940/plugin.video.tvvlaanderen-1.0.6%2Bmatrix.1.zip)

**Comment by steenkapper** [comment]
Sir,Can you explane how to find this log file.ThanksGCVerstuurd vanaf mijn iPhoneOp 25 jul. 2023 om 19:26 heeft Michaël Arnauts ***@***.***> het volgende geschreven:﻿
I don't have a TV Vlaanderen subscription anymore unfortunately, so I can't check myself.
I would need to have access to your logs to see what's going on.
Make sure to check in your browser on your profile page that you have not used all your device registrations. If it is, just remove an old one.
