### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by mediaminister** [add-ons/plugin.video.tvvlaanderen#7]
Does debug logging work? I can't get it working.
The default level of the Python logging module is `logging.WARNING` and all lower levels are ignored. So, if we want debug logging, shouldn't we set the log level with `logger.setLevel(logging.DEBUG)`?

**Comment by michaelarnauts** [comment]
Huh, you are right, I'm currently testing and developing with debugging turned on in Kodi (so I can also see the inputstream debug output). I've actually copied the `kodilogging.py` from VIER-VIJF-ZES, so I guess it's also not working there...
